# Linux MakeFile
# Variables
compiler = g++
pkgflags = `pkg-config --cflags --libs gtkmm-4.0`
target = Kry0Steg-GUI

# Targets -> File name generated by make
Kry0Steg-GUI: Kry0Steg-GUI.cpp
	$(compiler) Kry0Steg-GUI.cpp -o $(target) $(pkgflags)
